### ISSUE TITLE
Changing circle size

### ISSUE THREAD

**Issue by zacx01** [harpwood/Chord-Diagram-Creator-for-Adobe-Illustrator#2]
How do I change the circle size? It's a little too big, i'm not sure what number to put..

**Comment by harpwood** [comment]
Do you mean the circles that representing the fingering? Their size is adjusted automatically to fit between 2 frets. Customizing the thickness of the frets and the strings wont affect the circle's size.

However it is always possible to have encounter a bug. So if you stuck with odd graphical results, try to reset the line art. You can do it by  pressing the "Reset Line Art"  button which can be found on main window of this extension, after you expand it by ticking the "Show More" option.  If you still have issues, you can press the "Options" button -> "Set Defaults" tab -> "Factory reset" button.

Optionally, before make any action, you could send a screenshot with your diagram settings and the resulted chord diagram, so I could try to reproduce it and if a bug found to try fix it.

**Comment by harpwood** [comment]
Closed due to OP inactivity
